### ISSUE TITLE
Feature popup's width and show feature popups by fid

### ISSUE THREAD

**Issue by dimmer123** [jorix/OL-FeaturePopups#1] opened 2012-02-02 08:41 UTC
Don't know how to write direct messages on github, so I'll ask here. If the description is long popup stretches through the screen. Is it possible to set width of a feature popup?

**Comment by jorix** [comment] 2012-02-02 19:47
I think it is preferable control the size using CSS or inline styles.

For this reason **FeaturePopups** currently only offers this option, either in the template layer or with the display classes: `.olControlFeaturePopups_select` `.olControlFeaturePopups_hover` and `.olControlFeaturePopups_list`.

May be use a layer template like this:

```
<div style="width: 300px; margin-right:22px"><h2>${.title}</h2>${.description}</div>
    <!-- NOTE: `margin-right:22px` to ensure that there is room for the vertical scroll bar -->
```

If you use directly popups can also use this strategy but there are other tools with code.

You are using this `FeaturePopups` control? If so, keep using **issues** to any questions or suggestions.

**Comment by dimmer123** [comment] 2012-02-03 11:01
Thank you. I tried .olFramedCloudPopupContent { width: 300px; }; It works.

One more question. I use FeaturePopups on mgorka.info. When I drag a selection box and grab few markers in it a popup  appears well and doesn't disappear. But when I try to select a lot of markers (more than 100) a popup appears for a while, but soon disappears. I tried to repeat this behavior on test page http://jorix.github.com/OL-FeaturePopups/examples/feature-popups.html but I can't it works perfectly. So, there is something wrong with my files.

**Comment by jorix** [comment] 2012-02-03 15:52
I think the problem is as follows:

If you use strategies such as `Cluster` or `BBOX` when you move the map or zoom all features are reloaded. And to show a long Popup the map is moved to center the Popup, so features are reloaded oops!

Try: 

```
... = new OpenLayers.Control.FeaturePopups({ ..., refreshOnFeaturesremoved:false });
```

But this solution now has a difficulty, because the new `feature.id` will be different and the click on the list will not work. 

Try also with the approach [feature-popups-external.html](http://jorix.github.com/OL-FeaturePopups/examples/feature-popups-external.html)

New work?:
- Select the features by `fid` (id from the server) instead of `id` (if the `fid` exists) 

NOTE: I did not work in this area waiting for a use to justify it.

---

Your server assigns a unique `id` to its features? If so:
- You think it would be useful to use `fid` instead of `id` to display a popup from a list? 
- And re-select the features by `fid`??

**Comment by dimmer123** [comment] 2012-02-03 18:39
Yes, it's exactly as you wrote. I use both strategies Cluster and BBOX, so now I understand why features disappear. Thank you for explanation.
I tried <code>refreshOnFeaturesremoved:false</code>. As you said, popup doesn't close but list doesn't work. Well, actually it is not essential for me to load hundreds of items to the list. So the present version is OK. But if some day it  will be possible it would be great.
I load markers from Mysql database with the help of a php script. It grabs everything which is in bbox borders. Database tables don't have a particular column for id. Tables' structure is the same as in OpenLayers.Layer.Text <code>lat  lon title   description icon    iconSize    iconOffset</code>

<hr>

<code>You think it would be useful to use fid instead of id to display a popup from a list?
          And re-select the features by fid??</code>
Well I'm not a programmer so either fid or id is equal for me )). Maybe it's possible to stop map from refreshing when the popup with the list is open?

**Comment by jorix** [comment] 2012-02-03 19:34
> Well I'm not a programmer so either fid or id is equal for me

The `id` is generated by OpenLayers, so a feature does not have a proper `id` (not have the same id all the time), `fid` is read from 'id' in the data sent by the server, the feature always has the same `fid`.

> Maybe it's possible to stop map from refreshing when the popup with the list is open?

I think not, we would do a monster ungovernable, there are many OpenLayers events in the game :(

Think you to add a self incrementable `id` in the table, I think this may be a good option for the future. I would try to make adjustments in control  (and adjustments in OpenLayers.Layer.Text, I believe that this format does not store the id in `feature.fid`) I will do some experiments...

How about?

**Comment by dimmer123** [comment] 2012-02-03 20:21
Ok, let's try.

**Comment by jorix** [comment] 2012-02-05 19:34
See 6c41c77c5b1b9436f727f3c025ae8c0b08aa8213 used in example:
 http://jorix.github.com/OL-FeaturePopups/examples/georss-flickr.html

It is a first step. Now the list works, but may have features that have disappeared (zoom or move the map)

Next step: re-selected by `fid` (this is a bit more delicate)

**Comment by jorix** [comment] 2012-02-07 19:33
@dimmer123: You can start testing lists after zoom and the re-selection (requires the use of `fid`) 

(I think there are only small adjustments to make if I see something going wrong)

These days I have planned to do some tests on different scenarios.

**NOTE**:  
- Use `${showPopup(fid)}` instead of `${showPopup()}`  
- `refreshOnFeaturesremoved` APIProperty has become `refreshAction` (the default is automatic re-selection)

**Comment by dimmer123** [comment] 2012-02-08 14:01
Maybe I did something wrong, but it doesn't work. I added an auto_increment column to the database and to the script. The script grabs a fid number, it is shown in Popup. I changed showPopup() to showPopup(fid). Here is a test page http://mgorka.info/test/fp/index.html

**Comment by jorix** [comment] 2012-02-08 22:27
Ok, is necessary to do a little trick with the format, try:

```
     format: new OpenLayers.Format.Text({extractStyles: true,
           read: function(text) {
                var features = OpenLayers.Format.Text.prototype.read.apply(this, arguments);
                for (var i= 0, len = features.length; i < len; i++) {
                    features[i].fid = features[i].attributes.fid;
                }
                return features;
          }
     }),
```

**Comment by dimmer123** [comment] 2012-02-09 12:49
Now it works perfectly. Thank you.

Now I try to change the height of the popup with the list, so that it doesn't push the map. Don't know why it hadn't come to my mind before, because when the popup has a defined size it doesn't cause map movement and refresh. It would work with the old version of FeaturePopup. Shame on me. 
Anyway, I tried the recipe you wrote above
 <code>itemPopupTemplate:div style="height 400px;</a></li>",</code> Can't paste the whole right line, this editor crops it. But I get an error <code>missing } after property list</code> It doesn't like quotes in div style="height: 400px;"

**Comment by jorix** [comment] 2012-02-09 16:39
You need to escape quotes as:

```
itemPopupTemplate: "<div style=\"height 400px;\"> ...
```

There is no shame ;-)  work on `fid` is still needed when zooming.

**Comment by dimmer123** [comment] 2012-02-10 15:38
<blockquote><code>\"height 400px;\"</code></blockquote>

This helped to avoid the error, but popup's height remained unchanged.
Finally, I've found the solution: <code>.olControlFeaturePopups_list{height: 400px;}</code>

By the way, do you know why in Opera markers become bigger and bigger with every box drag? If shift is pressed it's OK, but with ctrl they grow.

**Comment by jorix** [comment] 2012-02-10 15:51
Sorry, I neglected the two point, is `itemPopupTemplate: "<div style=\"height: 400px;\">...` but it is cleaner using the class `.olControlFeaturePopups_list`

Curious behavior of Opera, this deserves to open an incident in OpenLayers? Can be reproduced with more simple examples of OL?

**Comment by jorix** [comment] 2012-02-10 16:04
Opps! itemPopupTemplate not serves to do this, only the class, you are right!

**Comment by dimmer123** [comment] 2012-02-10 20:48
<blockquote>Curious behavior of Opera, this deserves to open an incident in OpenLayers? Can be reproduced with more simple examples of OL?</blockquote>

Maybe it's Opera's fault. Markers stay stable in Firefox and Chrome.
Here is a simple example http://openlayers.org/dev/examples/dynamic-text-layer.html . It doesn't draw a box with ctrl, but markers grow anyway.

**Comment by jorix** [comment] 2012-03-14 18:54
I close this issue. 

I think the issues discussed here are solved (except Opera that is a problem of OpenLayers)

@dimmer123: Feel free to say if you do not think so.

**Closed as completed by jorix** 2012-03-14 18:54 UTC
Labels: Improvement

**Comment by jorix** [comment] 2012-06-08 21:42
Hi @dimmer123 

Recently, the control code has changed significantly. Currently the control is incompatible with the previous version, but offers several improvements. The code is now in consolidation phase and no changes are envisaged that could cause more incompatibility with the previous version.

Now is added suport for minSize and maxSize as:

```
var fpControl = new OpenLayers.Control.FeaturePopups({
    popupSingleOptions: {maxSize:{h:300}, minSize:{h:200}},
...
}
```

If you keep using this control I can guide you to switch to using the new version.

Regards,

Jorix
