### ISSUE TITLE
How to close all popups on zoom?

### ISSUE THREAD

**Issue by bogdandragomir** [jorix/OL-FeaturePopups#7] opened 2012-12-09 23:53 UTC
Do you have a simple solution to close all popups when the user zoom in or out?
Because after this operation the popup does not close when you click outside of it.

I think this is an Openlayers bug. I found online references about this from 2009.
Thank you!

**Comment by jorix** [comment] 2012-12-10 08:44
@bogdandragomir

> Do you have a simple solution to close all popups when the user zoom in or out?

May be canceled SAFE_SELECTION mode, but... what you have observed seems a bug:

> Because after this operation the popup does not close when you click outside of it.

This looks like a FeaturePopups bug. this afternoon I'll look in detail.

**Comment by bogdandragomir** [comment] 2012-12-10 10:39
I don't think this is a FeaturePopups bug because in this OpenLayers example the behaviour is the same:
http://openlayers.org/dev/examples/dynamic-text-layer.html

But on these examples it works fine:
http://openlayers.org/dev/examples/sundials.html
http://openlayers.org/dev/examples/sundials-spherical-mercator.html

**Comment by jorix** [comment] 2012-12-10 21:00
@bogdandragomir 

> I don't think this is a FeaturePopups bug

yes, you are right, but... 

FeaturePopups wraps the SelectFeature behavior, so... I will try to do a bypass this problem.

A little light on the problem (for now without touching code): The strategies "BBOX" and "Cluster" cause after a zoom miss selection since the features of the layer are renewed after the zoom. The FeaturePopups has a hidden part that is SAFE_SELECTION mode fighting to prevent this. But until now I was worried about  clickout+SAFE_SELECTION. 

... I'll try to hide this problem under the cloak of SAFE_SELECTION.

NOTE: This week I think will it take a few days on could work on it.

**Comment by jorix** [comment] 2012-12-10 22:40
...seems that the first attempt it worked, I'm a little surprised ... anything can go wrong¿? :--|

@bogdandragomir  could you try 4b51141cea5f9ef99dfb7b1e4f27df1d8a3df56e ?

**Comment by bogdandragomir** [comment] 2012-12-10 23:01
Yes, it works. You can see it in action here: http://test2.trafficguide.ro/. But there are still two problems:
1. In some conditions the second popup is closed on zoom out.
2. If you zoom-in the two popups (cluster and event) are anchored on very different points, see attached screen shot.

And I have another observation: if I zoom in a few times and than zoom out the same times the clusters are not created as they were on the page load. Is this the correct behaviour?

Thank you!

![snap172.jpg](https://f.cloud.github.com/assets/2846921/4685/fe4ccd4e-431c-11e2-87ee-0397c2987f86.jpg)

**Comment by jorix** [comment] 2012-12-11 17:27
@bogdandragomir 

> 1 In some conditions the second popup is closed on zoom out.

Yes, I could reproduce the problem... I am investigating...

> 2 If you zoom-in the two popups (cluster and event) are anchored on very different points

Yes... so far the insertion point of the popup is the cursor position (is useful in lines and polygons) 

you are right: this in clusters is confusing when zooming, now is the center point of the boundaries (rectangle) of the cluster points.  See dd7072269742b58006432c1d50159a120c97ee38

>  if I zoom in a few times and than zoom out the same times the clusters are not created as they were on the page load. Is this the correct behaviour?

I do not see a reason for this behavior: AFAIK strategy has a cache of the features, and each zoom read the features in the same order to make the clusters. 

I noted that the page is reloaded periodically, I do not know if it can be related¿?

**Comment by bogdandragomir** [comment] 2012-12-11 22:09
The 2nd point is working OK now. Thank you!

I don't think the clusters are not the same after zoom in-out because of the periodically refresh.
The refresh is acting each 5 minutes, but I can see this problem in the first 10 seconds after the page is loaded.
It is just a simple META REFRESH tag.

And e new question for you:
Could it be possible to zoom with the scroll wheel when the mouse is in the popup active area?
Now it is not possible and because the zoom center on the mouse position it is a bit frustrating I can not zoom on the anchor point of the opened popup.

**Comment by jorix** [comment] 2012-12-12 22:45
@bogdandragomir 

> The 2nd point..

Ok :-)

I have yet to get back first point, but honestly I have not gone to look for now :-(

> ...but I can see this problem in the first 10 seconds after the page is loaded.

Is it related to the FeaturePopups control? The problem also occurs if FeaturePopups is not used?

> Could it be possible to zoom with the scroll wheel when the mouse is in the popup active area?

I thought it would be quite difficult... but looking handler code I think I found a back door left open by the OL team, try: d4b2fe9cda06b587c01d9841f6be6f24eff3b98c (in the example is only active for single popup, should also be added to `popupListOptions` and `popupListItemOptions`)

... but I do not know if this will have side effects.

**Comment by jorix** [comment] 2012-12-13 23:37
@bogdandragomir 

> 1. In some conditions the second popup is closed on zoom out.

After debug I think I've found. Try to use the current control. 

(I fixed a bug 699af5f9c69ca34947653bea28ef9a7575ea26f4 a few days, you are using an earlier version. I thought you had already updated the control so you used newer patches like 4b51141cea5f9ef99dfb7b1e4f27df1d8a3df56e )

---

*\* **fid** about **: 

FeaturePopups control uses the **fid** thinking that is unique in the layer (id attribute)

I thought that one day it would be interesting to ignore the fid if there was a reason to justify it. In your case requires off, so **fid is not unique** (eg fid=13 are "Camera Rovigneta 10" and "GATSO 179", after zooming this will cause a addicional selection of all fid=13)

**I'll work on it**.

**Comment by bogdandragomir** [comment] 2012-12-14 13:51
I updated the file FeaturePopups.js and yes, it looks like the bug "In some conditions the second popup is closed on zoom out.".

I did not know you update it with all patches you sent to me for testing and even now I am not sure, because some of them you marked as 'experimental'.

**Comment by bogdandragomir** [comment] 2012-12-14 14:03
I updated the code with d4b2fe9 patch here http://test2.trafficguide.ro/ but nothing changed. 
Please check. 

Also I updated the FeaturePopups.js used on the test site and it looks like the problem "In some conditions the second popup is closed on zoom out." is solved.

Thank you!

**Comment by jorix** [comment] 2012-12-14 17:31
Hi Bogdan,

Well! :-)

Today there is something wrong with GitHub, I do not see your responses in
OL-FeaturePopups/issues, and I have received four or more times this
message.

Xavier Mamano

---

De: Bogdan [mailto:notifications@github.com] 
Enviado el: viernes, 14 de diciembre de 2012 18:04
Para: jorix/OL-FeaturePopups
CC: Xavier Mamano
Asunto: Re: [OL-FeaturePopups] How to close all popups on zoom? (#7)

I updated the code with
https://github.com/jorix/OL-FeaturePopups/commit/d4b2fe9 d4b2fe9 patch
here http://test2.trafficguide.ro/ but nothing changed. 
Please check. 

Also I updated the FeaturePopups.js used on the test site and it looks like
the problem "In some conditions the second popup is closed on zoom out." is
solved.

Thank you!

## 

Reply to this email directly or view
https://github.com/jorix/OL-FeaturePopups/issues/7#issuecomment-11383561
it on GitHub. 

<https://github.com/notifications/beacon/AbWkxnmM90IPlQrEr6FQKy2lO28Rg4u29Ui
9WTHfEs2UJuu23-yVX-8O-P-LdWAX.gif>

**Comment by jorix** [comment] 2012-12-16 13:44
Not! :( it still the same.

I only see my comments on the issues that you have opened (even without
identifying in GitHub as jorix)

---

De: Bogdan [mailto:notifications@github.com] 
Enviado el: sábado, 15 de diciembre de 2012 19:56
Para: jorix/OL-FeaturePopups
CC: Xavier Mamano
Asunto: Re: [OL-FeaturePopups] How to close all popups on zoom? (#7)

Let's see. Is it working today?

—
Reply to this email directly or view
https://github.com/jorix/OL-FeaturePopups/issues/7#issuecomment-11408914
it on GitHub. 

<https://github.com/notifications/beacon/AbWkxnmM90IPlQrEr6FQKxQ9ebBuxIKysc3
cHhJkBdAfZ16rIFYgTUeSQjGPNRae.gif>

**Comment by jorix** [comment] 2012-12-24 16:22
@bogdandragomir  ... and in this issue, there is something pending?

**Comment by jorix** [comment] 2012-12-27 22:21
@bogdandragomir  I think I have the answer to this old question.

> if I zoom in a few times and than zoom out the same times the clusters are not created as they were on the page load. Is this the correct behaviour?

I worry about the problem was related to the control, I think not...

Is associated with the functions `clusterDeactivate` and `clusterActivate` on "harta.js", since these funtions cause to make the cache of the cluster again but in a different order by `c.layer.addFeatures(features); c.clearCache();`

Maybe it would solve the problem by sorting `features` by id (but numeric order only by the part numerical of the id)

( Curious: We walked separately by the same `OpenLayers.Strategy.Cluster` limitation, when you mentioned it I thought it was a weakness that had my proposal https://github.com/openlayers/openlayers/pull/756 )

**Comment by jorix** [comment] 2012-12-28 15:22
...and more: at the end of `clusterActivate` there are:

```
  c.layer.addFeatures(features);
  c.clearCache();
```

this `c.clearCache();` after addFeatures causes that the cluster method not act.

**Comment by bogdandragomir** [comment] 2012-12-28 22:30
You are right in the last comment! 
When I comment the `c.clearCache()` line from the `function clusterActivate(c)` the clusters are recreated correct when zoom out.

I think this is enough for this thread, no need for sorting features by id.
Thank you very much!

PS: I found those two functions for activate/deactivate the cluster strategy somewhere online. I hope if somebody have the same problem to find this page and your solution.

**Comment by jorix** [comment] 2012-12-28 22:55
I think in this case this would also work (not tested)

```
function clusterDeactivate(c) {
    if (c.active) {
        var features = c.features.slice();
        c.deactivate();
        c.layer.removeAllFeatures();
        c.layer.addFeatures(features);
    }
}
function clusterActivate(c) {
    c.activate();
}
```

**Comment by bogdandragomir** [comment] 2012-12-29 00:11
It doesn't work. 

When zoom in than zoom out the clusters are not recreated.
And if I zoom in again (so zoom in, zoom out, zoom in) I see this error:

```
TypeError: c.features is null

var features = c.features.slice();
```

But do you think it is necessary to find a better/shorter solution for this?
I think it is a very rarely used feature if it is not in the OpenLayers library yet.

**Comment by jorix** [comment] 2012-12-29 00:23
> But do you think it is necessary to find a better/shorter solution for this?

I think not (but for me it is always a temptation) 

> I think it is a very rarely used feature if it is not in the OpenLayers library yet.

But it seems very reasonable behavior. Sometimes there are several users who stumble at the same stone, and the stone remains in the same place. The OL team does not have time for all details.

**Comment by bogdandragomir** [comment] 2012-12-29 00:46
If you find a working solution I think it could be placed inside your file _patches_OL-popup-autosize.js_ until OL team will accept it in their distribution.

**Comment by jorix** [comment] 2012-12-31 19:46
> If you find a working solution I think it could be placed inside your file patches_OL-popup-autosize.js until OL team will accept it in their distribution.

See: [Cluster-patch.js](https://github.com/jorix/OL-Ragbag/blob/fa2a09735e487b468cf1ee5023ac8ed4773ac6fd/lib/Ragbag/Strategy/Cluster-patch.js) used in example: [sundials-cluster.html](http://jorix.github.com/OL-Ragbag/examples/sundials-cluster.html) 

Currently under development ;-)

**Comment by drupol** [comment] 2013-01-02 12:26
Hello,

I'm one of the maintainer in charge of the [OpenLayers module](http://drupal.org/project/openlayers) for Drupal.
I came accross your project while searching for a way to get popup working correctly when cluster is enabled.

I see in this [example](http://jorix.github.com/OL-FeaturePopups/examples/feature-popups.html) that closing the popup is still working even after zooming in or out.
Now, if we take this [example](http://jorix.github.com/OL-Ragbag/examples/sundials-cluster.html) it doesn't work.

We are having the same bug in our module, and I would like to get it fixed, [this is the code in charge for the popup part](http://drupalcode.org/project/openlayers.git/blob/refs/heads/7.x-2.x:/plugins/behaviors/openlayers_behavior_popup.js).

Don't hesitate to join the [discussion](http://drupal.org/node/1369012), any comment are welcome !!!

Many thanks in advance :)

**Comment by drupol** [comment] 2013-01-02 15:20
I've finally ended up writing a custom module implementing your library and I have to say that it works pretty good, no bug to report !!

You can see the code here: http://drupal.org/sandbox/Pol/1877914

I'll see if I include it in the OpenLayers module.

**Comment by jorix** [comment] 2013-01-02 19:19
Hello @Polzme 

What an honor! :-)

> I see in this example that closing the popup is still working even after zooming in or out.

Effectively, is the mode SAFE_SELECTION. 

This mode uses by default the `fid` (server feature id) when exists, and in this case it is **very important**
that there are **no duplicate** `fid`. Otherwise should be forced the use of the `id` generated by OL. 

OL module for Drupal uses other strategies than Cluster? (BBOX, Refresh)

We could talk more about it...

> Now, if we take this example it doesn't work.

Is an example of another repository. FeaturePopups is not used there (uses SelectFeature)

> You can see the code here: http://drupal.org/sandbox/Pol/1877914

Some comments about:
- `Drupal.theme.prototype.openlayersPopupHoverList = function(feature) {...` the argument is not a `feature`, is a `listObj`. The name of the argument can confuse someone (although no matter to work properly)
- Is there a problem use e.g.:

```
   Drupal.theme.prototype.openlayersPopupHoverList = function() {
     return '<b>${count}</b><br>${html}';
   }
   ... and ...
  templates.hoverList = Drupal.theme('openlayersPopupHoverList', null);
```

 (If it's silly, forget it, --for now I have not used the Drupal--)
- As `Drupal.theme.prototype.openlayersPopupItem` is now defined, the elements into a list popup do not allow open a popup with details of a single feature, are not interested in using this option?

Open a new issue for any questions or problems you have with the control. I will be very happy to help you.

**Comment by jorix** [comment] 2013-01-02 21:58
Hi @Polzme 

This should be the beginning of my explanations

> I see in this example that closing the popup is still working even after zooming in or out.
> +
> Now, if we take this example it doesn't work.

to close the popups on [sundials-cluster.html](http://jorix.github.com/OL-Ragbag/examples/sundials-cluster.html) (from the other repository) is used: 

```
function onPopupClose(evt) {
    select.unselectAll();
}
```

but this is a nomal OL code. So after a zoom nothing is selected so `select.unselectAll();` does nothing because there is nothing to do. So is a problem but is not a OL bug.

But see [feature-popups.html](http://jorix.github.com/OL-FeaturePopups/examples/feature-popups.html) after zoom the features remain selected. So being can do something to skip the problem but using SAFE_SELECTION.

**Comment by drupol** [comment] 2013-01-02 22:55
Hello @jorix,

Thanks for your time replying me !

I've already included your changes into the module Drupal, thanks.
The way it works is perfect for Drupal because it's really easy to override a theme function.

I still do not understand what you mean by:

> As Drupal.theme.prototype.openlayersPopupItem is now defined, the elements into a list popup do not allow open a
> popup with details of a single feature, are not interested in using this option?

Could you give me more details ?

About the sundials-cluster.html, ok I got it, I see now :)

It's sad that you don't use Drupal, key people like you would be helpful in the OpenLayers module :)

Have a good evening and thanks again !

**Comment by jorix** [comment] 2013-01-02 23:11
> Could you give me more details ?

Yes, see at [feature-popups.html](http://jorix.github.com/OL-FeaturePopups/examples/feature-popups.html)

If you select a cluster displays a list, and from there you can use the links to see an item. This requires a text template (not a function) that has `"<li ${showPopup()}>...</li>"` at least.

**Comment by jorix** [comment] 2013-01-02 23:16
@Polzme 

and more...

I see this "openlayers_behavior_popup.js" code:

```
  64         popup = new OpenLayers.Popup.FramedCloud(
  65           'popup',
  66           feature.geometry.getBounds().getCenterLonLat(),
  67           null,
  68           Drupal.theme('openlayersPopup', feature),
  69           null,
  70           true,
  71           function(evt) {
  72             Drupal.openlayers.popup.popupSelect.unselect(selectedFeature);
  73           }
  74         );
```

FeaturePopups is not compatible with: 
`Drupal.openlayers.popup.popupSelect.unselect(selectedFeature);` 
so:

The point of view of FeaturePopups is that there can only be one active popup. The behavior is: if more than one feature is selected is shown one popup with the list of features, regardless of whether it is a cluster, a multi selection or selection box, or all things at once.
(is allowed the pair: list + item, and even a trio: list + item + hover, but no more!)

**Comment by drupol** [comment] 2013-01-02 23:21
@jorix,

Those files are OpenLayers behaviors, from Drupal, you can assign 1 or multiple behaviors to a map.
In this case, this file is the default popup behavior for the OpenLayers module.

The [new module I created](http://drupal.org/sandbox/Pol/1877914) is using your extension and provides a new behavior to the OpenLayers module.

Both behaviors, the default popup behavior and the new one shouldn't be enabled at the same time.

Now, the new module is just a sandbox module, it means that it's not yet a full module, I'm still testing and evaluating it. If I'm good with it, I'll probably include your extension in the next beta release of the OpenLayers module.

If you need more information on how OpenLayers works in Drupal, don't hesitate to send me a mail :)

Thanks !

**Comment by drupol** [comment] 2013-01-03 08:40
Ok, I know what I'm gonna do.

In order to use your library in Drupal, I don't have a lot of choice.

Bundling the library in the module itself is not a good practice. why ?
Because the library may evolve at a different pace than the module and, it's not a good Drupal practice.

The other possibility is to modify OpenLayers module and include your library from GitHub.
For example:

``` html
  <script src='https://raw.github.com/jorix/OL-FeaturePopups/gh-pages/lib/FeaturePopups.js' type='text/javascript'></script>
```

The problem here is that we are depending on a new host and the page will be slower to load.
By default, the OL module load the library from: http://openlayers.org/api/2.12/OpenLayers.js, adding a new host for an extra part is already better than the previous solution, but still bad.

The only choice I have is to create an extra module who will implement a new behavior, a new popup behavior.
In order to work, the FP extension will need to be downloaded by the user and the module will automatically use it, and can be upgraded without the need to upgrade the module.

I think I'll release it today, but before, I need to fix the current popup behavior in the OL module and maybe I'll need a help hand from you if you're ok.
Once this is fixed, I'll release a new beta and a module based on your extension.

All I really hope is that FP gets included in OL, it's much more better than the default popup management !

Thanks for your time !

**Comment by jorix** [comment] 2013-01-03 14:49
@Polzme Now I do not have time, I comment on your comments later. But I thought it best to follow in a separate issue #10.

(This is a project done in my spare time, usually in the afternoons I can work on this)

**Comment by jorix** [comment] 2013-01-07 17:24
I close this issue, it seems that there are no problems here.

@bogdandragomir Until next time ;-)

**Closed as completed by jorix** 2013-01-07 17:24 UTC
Labels: Improvement

**Comment by bogdandragomir** [comment] 2013-01-07 19:02
Thank you Jorix!
See you soon :)

**Comment by drupol** [comment] 2013-01-07 20:09
yeah, sorry for trying to hijack your thread @bogdandragomir :-)

**Comment by bogdandragomir** [comment] 2013-01-07 20:19
No problem Polzme. Now I receive all emails sent by you and I don't know what to do :)
But in this way I am learning to use github.

**Comment by drupol** [comment] 2013-01-07 20:20
GitHub is the best social network for developpers, a heaven on earth :)

Happy learning !
